const vertraege = [
  { kategorie: "Gläubiger", name: "DSL Bank", monatlich: 720.00, rhythmus: 1 },
  { kategorie: "Auto", name: "VW Touran", monatlich: 350.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Gas", monatlich: 200.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Kindergarten", monatlich: 150.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "LBS Süd", monatlich: 150.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Strom", monatlich: 93.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "1&1", monatlich: 65.00, rhythmus: 1 },
  { kategorie: "Versicherungen", name: "Unfall Natascha", monatlich: 32.50, rhythmus: 6 },
  { kategorie: "Versicherungen", name: "KFZ Versicherung", monatlich: 32.08, rhythmus: 6 },
  { kategorie: "Gläubiger", name: "LUK", monatlich: 63.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Helvetia (Rücklagen)", monatlich: 60.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "VW Leasing", monatlich: 57.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Grover", monatlich: 50.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Kai Handy (mobilcom-debitel)", monatlich: 37.00, rhythmus: 1 },
  { kategorie: "Versicherungen", name: "Rechtsschutz", monatlich: 15.75, rhythmus: 6 },
  { kategorie: "Versicherungen", name: "Concordia Rechtsschutz", monatlich: 15.42, rhythmus: 6 },
  { kategorie: "Versicherungen", name: "Wohngebäude", monatlich: 26.92, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Abfallgebühren", monatlich: 12.50, rhythmus: 6 },
  { kategorie: "Versicherungen", name: "Risikoleben", monatlich: 23.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Rundfunkbeitrag", monatlich: 18.42, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Spotify", monatlich: 15.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Telekom", monatlich: 15.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "KFZ Steuer", monatlich: 12.50, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Grundsteuer", monatlich: 2.71, rhythmus: 3 },
  { kategorie: "Versicherungen", name: "Hausrat", monatlich: 10.17, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Google One", monatlich: 10.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Amazon", monatlich: 9.00, rhythmus: 1 },
  { kategorie: "Versicherungen", name: "Tierhalterhaftpflicht", monatlich: 4.25, rhythmus: 6 },
  { kategorie: "Gläubiger", name: "Hundesteuer", monatlich: 8.33, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Disney+", monatlich: 8.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "ADAC", monatlich: 6.58, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "Privathaftpflicht", monatlich: 3.17, rhythmus: 6 },
  { kategorie: "Gläubiger", name: "Soldatenkameradschaft", monatlich: 2.25, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "Auslandsreise", monatlich: 1.75, rhythmus: 12 }
];