const vertraege = [
  { kategorie: "Gläubiger", name: "DSL Bank", monatlich: 720.00, rhythmus: 1 },
  { kategorie: "Auto", name: "VW Touran", monatlich: 350.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Gas", monatlich: 200.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Kindergarten", monatlich: 150.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "LBS Süd", monatlich: 150.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Strom", monatlich: 93.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "1&1", monatlich: 65.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "LUK", monatlich: 63.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Helvetia (Rücklagen)", monatlich: 60.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "VW Leasing", monatlich: 57.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Grover", monatlich: 50.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Kai Handy (mobilcom-debitel)", monatlich: 37.00, rhythmus: 1 },
  { kategorie: "Versicherungen", name: "Unfall Natascha", monatlich: 65.00 / 12, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "KFZ Versicherung", monatlich: 193.00 / 6, rhythmus: 6 },
  { kategorie: "Versicherungen", name: "Wohngebäude", monatlich: 323.00 / 12, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "Risikoleben", monatlich: 276.00 / 12, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Rundfunkbeitrag", monatlich: 221.00 / 12, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "Rechtsschutz", monatlich: 378.00 / 6, rhythmus: 6 },
  { kategorie: "Versicherungen", name: "Concordia Rechtsschutz", monatlich: 93.00 / 6, rhythmus: 6 },
  { kategorie: "Gläubiger", name: "Spotify", monatlich: 15.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Telekom", monatlich: 15.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Abfallgebühren", monatlich: 300.00 / 6, rhythmus: 6 },
  { kategorie: "Gläubiger", name: "KFZ Steuer", monatlich: 150.00 / 12, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "Hausrat", monatlich: 122.00 / 12, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Google One", monatlich: 10.00, rhythmus: 1 },
  { kategorie: "Gläubiger", name: "Amazon", monatlich: 9.00, rhythmus: 1 },
  { kategorie: "Versicherungen", name: "Tierhalterhaftpflicht", monatlich: 51.00 / 6, rhythmus: 6 },
  { kategorie: "Gläubiger", name: "Hundesteuer", monatlich: 100.00 / 12, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Disney+", monatlich: 8.00, rhythmus: 1 },
  { kategorie: "Versicherungen", name: "Privathaftpflicht", monatlich: 90.00 / 12, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "ADAC", monatlich: 79.00 / 12, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Grundsteuer", monatlich: 33.17 / 3, rhythmus: 3 },
  { kategorie: "Gläubiger", name: "Soldaten", monatlich: 29.00 / 12, rhythmus: 12 },
  { kategorie: "Gläubiger", name: "Soldatenkameradschaft", monatlich: 27.00 / 12, rhythmus: 12 },
  { kategorie: "Versicherungen", name: "Auslandsreise", monatlich: 21.00 / 12, rhythmus: 12 }
];