const vertraege = [
    { kategorie: "Kredite", name: "DSL Bank", jaehrlich: 8640, monatlich: 720.00 },
    { kategorie: "Auto", name: "VW Touran", jaehrlich: 4200, monatlich: 350.00 },
    { kategorie: "Gläubiger", name: "Kindergarten", jaehrlich: 1800, monatlich: 150.00 },
    { kategorie: "Kredite", name: "LBS Süd", jaehrlich: 1800, monatlich: 150.00 },
    { kategorie: "Gläubiger", name: "Gas", jaehrlich: 2400, monatlich: 200.00 },
    { kategorie: "Gläubiger", name: "Strom", jaehrlich: 1116, monatlich: 93.00 },
    { kategorie: "Gläubiger", name: "1&1", jaehrlich: 780, monatlich: 65.00 },
    { kategorie: "Gläubiger", name: "LUK", jaehrlich: 756, monatlich: 63.00 },
    { kategorie: "Gläubiger", name: "Helvetia (Rücklagen)", jaehrlich: 720, monatlich: 60.00 },
    { kategorie: "Gläubiger", name: "Grover", jaehrlich: 600, monatlich: 50.00 },
    { kategorie: "Versicherungen", name: "Rechtsschutz", jaehrlich: 378, monatlich: 31.50 },
    { kategorie: "Versicherungen", name: "Wohngebäude", jaehrlich: 323, monatlich: 26.92 },
    { kategorie: "Gläubiger", name: "Abfallgebühren", jaehrlich: 300, monatlich: 25.00 },
    { kategorie: "Versicherungen", name: "Risikoleben", jaehrlich: 276, monatlich: 23.00 },
    { kategorie: "Gläubiger", name: "Rundfunkbeitrag", jaehrlich: 221, monatlich: 18.42 },
    { kategorie: "Gläubiger", name: "Spotify", jaehrlich: 180, monatlich: 15.00 },
    { kategorie: "Gläubiger", name: "Telekom", jaehrlich: 180, monatlich: 15.00 },
    { kategorie: "Gläubiger", name: "KFZ Steuer", jaehrlich: 150, monatlich: 12.50 },
    { kategorie: "Gläubiger", name: "Grundsteuer", jaehrlich: 130, monatlich: 10.83 },
    { kategorie: "Versicherungen", name: "Hausrat", jaehrlich: 122, monatlich: 10.17 },
    { kategorie: "Gläubiger", name: "Google One", jaehrlich: 120, monatlich: 10.00 },
    { kategorie: "Gläubiger", name: "Amazon", jaehrlich: 108, monatlich: 9.00 },
    { kategorie: "Gläubiger", name: "Hundesteuer", jaehrlich: 100, monatlich: 8.33 },
    { kategorie: "Versicherungen", name: "Privathaftpflicht", jaehrlich: 89, monatlich: 7.42 },
    { kategorie: "Gläubiger", name: "ADAC", jaehrlich: 79, monatlich: 6.58 },
    { kategorie: "Versicherungen", name: "Unfall Natascha", jaehrlich: 780, monatlich: 65.00 },
    { kategorie: "Versicherungen", name: "Tierhalter", jaehrlich: 62, monatlich: 5.17 },
    { kategorie: "Gläubiger", name: "Soldaten", jaehrlich: 27, monatlich: 2.25 },
    { kategorie: "Versicherungen", name: "Auslandsreise", jaehrlich: 21, monatlich: 1.75 },
    { kategorie: "Gläubiger", name: "On That Ass", jaehrlich: 156, monatlich: 13.00 },
    { kategorie: "Gläubiger", name: "ChatGPT", jaehrlich: 96, monatlich: 8.00 }
];